import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { montserrat } from "./ui/fonts";
import { SessionProvider } from "next-auth/react";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.className}antialiased`}
      >
        <SessionProvider>
        <Navbar/>
          {children}
          </SessionProvider>
      </body>
    </html>
  );
}
